primary:
  initdb:
    scripts:
      init.sql: |
        SELECT 'CREATE DATABASE aztec_listener_devnet'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'aztec_listener_devnet')\gexec
        SELECT 'CREATE DATABASE aztec_listener_sp_testnet'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'aztec_listener_sp_testnet')\gexec
        SELECT 'CREATE DATABASE explorer_api_devnet'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'explorer_api_devnet')\gexec
        SELECT 'CREATE DATABASE explorer_api_sp_testnet'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'explorer_api_sp_testnet')\gexec
        SELECT 'CREATE DATABASE ethereum_listener_devnet'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'ethereum_listener_devnet')\gexec
        SELECT 'CREATE DATABASE ethereum_listener_sp_testnet'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'ethereum_listener_sp_testnet')\gexec
        SELECT 'CREATE DATABASE auth'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'auth')\gexec
        \c auth
        CREATE TABLE public."auth_api-keys" (
            id integer NOT NULL,
            "apiKey" uuid NOT NULL,
            "createdAt" timestamp with time zone NOT NULL,
            "updatedAt" timestamp with time zone NOT NULL
        );

        CREATE SEQUENCE public."auth_api-keys_id_seq"
            AS integer
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1;

        ALTER SEQUENCE public."auth_api-keys_id_seq" OWNED BY public."auth_api-keys".id;

        ALTER TABLE ONLY public."auth_api-keys" ALTER COLUMN id SET DEFAULT nextval('public."auth_api-keys_id_seq"'::regclass);

        COPY public."auth_api-keys" (id, "apiKey", "createdAt", "updatedAt") FROM stdin;
        1	d1e2083a-660c-4314-a6f2-1d42f4b944f4	2023-11-02 12:22:48.82+00	2023-11-02 12:22:48.82+00
        \.
        SELECT pg_catalog.setval('public."auth_api-keys_id_seq"', 1, true);
        ALTER TABLE ONLY public."auth_api-keys"
            ADD CONSTRAINT "auth_api-keys_pkey" PRIMARY KEY (id);
        CREATE UNIQUE INDEX "auth_api-keys_api_key" ON public."auth_api-keys" USING btree ("apiKey");

        SELECT 'CREATE DATABASE apikey'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'apikey')\gexec
        \c apikey
        CREATE TABLE public."api-key_api-keys" (
            id integer NOT NULL,
            "apiKey" uuid NOT NULL,
            "userId" character varying(255),
            "createdAt" timestamp with time zone NOT NULL,
            "updatedAt" timestamp with time zone NOT NULL
        );

        CREATE SEQUENCE public."api-key_api-keys_id_seq"
            AS integer
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1;

        ALTER SEQUENCE public."api-key_api-keys_id_seq" OWNED BY public."api-key_api-keys".id;

        ALTER TABLE ONLY public."api-key_api-keys" ALTER COLUMN id SET DEFAULT nextval('public."api-key_api-keys_id_seq"'::regclass);

        COPY public."api-key_api-keys" (id, "apiKey", "userId", "createdAt", "updatedAt") FROM stdin;
        1	d1e2083a-660c-4314-a6f2-1d42f4b944f4	\N	2023-11-02 12:22:48.82+00	2023-11-02 12:22:48.82+00
        \.
        SELECT pg_catalog.setval('public."api-key_api-keys_id_seq"', 67, true);
        ALTER TABLE ONLY public."api-key_api-keys"
            ADD CONSTRAINT "api-key_api-keys_pkey" PRIMARY KEY (id);
        CREATE UNIQUE INDEX "api-key_api-keys_api_key" ON public."api-key_api-keys" USING btree ("apiKey");
