apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-explorer-ui
  namespace: chicmoz
spec:
  ingressClassName: nginx
  rules:
    - host: explorer-ui.localhost
      http:
        paths:
          - backend:
              service:
                name: explorer-ui-sandbox-service
                port:
                  name: http-app
            path: /
            pathType: Prefix
    - host: sandbox.explorer-ui.localhost
      http:
        paths:
          - backend:
              service:
                name: explorer-ui-sandbox-service
                port:
                  name: http-app
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
