apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-helm-values
  namespace: chicmoz-prod
data:
  DYNAMIC_CONFIG_ENABLED: "true"
# To connect to kafka set the following from the dashboard
# Cluster name: "chicmoz"
# Bootstrap servers: kafka:9092
# Auth method: SASL/PLAIN
# Security protocol: SASL_PLAINTEXT
# Username: controller_user
# Password: test
