apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-explorer-api-sandbox
  namespace: chicmoz
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-url: http://auth.chicmoz.svc.cluster.local
    nginx.ingress.kubernetes.io/auth-response-headers: x-api-key
spec:
  rules:
    - host: explorer-api.localhost
      http:
        paths:
          - path: /v1/([^/]+)/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: explorer-api-sandbox-service
                port:
                  name: http-app
    - host: sandbox.explorer-api.localhost
      http:
        paths:
          - path: /v1/([^/]+)/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: explorer-api-sandbox-service
                port:
                  name: http-app
status:
  loadBalancer: {}
