apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ../anvil-ethereum-node/skaffold.yaml
deploy:
  kubectl:
    flags:
      apply: ["--force"]
manifests:
  rawYaml:
    - ../aztec-sandbox-node/ingress.yaml
    - ../aztec-sandbox-node/deployment.yaml
    - ../aztec-sandbox-node/service.yaml
    - ../anvil-ethereum-node/config.yaml
    - ../anvil-ethereum-node/ingress.yaml
    - ../anvil-ethereum-node/deployment.yaml
    - ../anvil-ethereum-node/service.yaml
